export function DisclaimerContent() {
  return (
    <>
      <p>
        PLEASE READ THIS DISCLAIMER CAREFULLY BEFORE USING NESTCALC. BY USING THE SERVICE, YOU
        ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS DISCLAIMER.
      </p>

      <h2>1. Not Financial Advice</h2>
      <p>
        NestCalc.ai, LLC is <strong>NOT</strong> a registered investment advisor, broker-dealer,
        financial planner, real estate broker, appraiser, or licensed professional of any kind.
        NestCalc.ai, LLC is not registered with the Securities and Exchange Commission (SEC), the
        Financial Industry Regulatory Authority (FINRA), or any state securities regulator.
      </p>
      <p>
        Nothing on this platform — including calculations, projections, AI-generated narratives,
        market intelligence reports, macro dashboards, or any other output — constitutes financial,
        investment, tax, or legal advice. No fiduciary relationship is created between you and
        NestCalc by your use of the Service.
      </p>
      <p>
        All content provided by NestCalc is for <strong>informational and educational purposes
        only</strong>. No output of the Service should be interpreted as a recommendation to buy,
        sell, hold, or finance any real estate property or investment.
      </p>

      <h2>2. Hypothetical Projections</h2>
      <p>
        All calculations, projections, scenarios, and analyses generated by NestCalc are
        entirely <strong>hypothetical</strong>. They are based solely on the inputs and assumptions
        you provide and do not represent actual investment results, returns, or guarantees of any kind.
      </p>
      <ul>
        <li>Projected cash flows, returns, appreciation rates, and equity positions are mathematical estimates — not predictions of future performance.</li>
        <li>Small changes in inputs (interest rate, vacancy rate, appreciation assumptions) can produce <strong>dramatically different outputs</strong>. Results are highly sensitive to the accuracy of your assumptions.</li>
        <li><strong>Past performance and historical data do not predict future results.</strong> Historical trends referenced in the Service may not continue, and market conditions can change rapidly and without warning.</li>
        <li>No projection accounts for all possible risks, including but not limited to: unexpected repairs, natural disasters, changes in local regulations, tenant defaults, interest rate fluctuations, or economic downturns.</li>
      </ul>

      <h2>3. AI-Generated Analysis Limitations</h2>
      <p>
        NestCalc integrates multiple artificial intelligence services to generate market
        intelligence, deal narratives, and economic analysis:
      </p>
      <ul>
        <li><strong>Perplexity Sonar</strong> — Local market intelligence (demographics, trends, property valuations) for paid tiers</li>
        <li><strong>Anthropic Claude</strong> — AI deal narratives and investment commentary for paid tiers</li>
        <li><strong>Google Gemini</strong> — Macro economic dashboards and market analysis for all tiers</li>
        <li><strong>FRED API</strong> — Treasury yields and mortgage rate data from the Federal Reserve for all tiers</li>
      </ul>
      <p><strong>You acknowledge and accept the following limitations:</strong></p>
      <ul>
        <li>AI models may produce <strong>inaccurate, incomplete, outdated, or misleading information</strong>. AI models are known to "hallucinate" — generating plausible-sounding content that is factually incorrect.</li>
        <li>Market data, demographic statistics, neighborhood descriptions, and property valuations generated by AI are <strong>estimates — not verified appraisals</strong>. They have not been reviewed or confirmed by licensed professionals.</li>
        <li>Interest rates displayed from the FRED API are <strong>indicative national averages</strong>. Actual rates you receive will depend on your individual creditworthiness, lender terms, loan type, and market conditions at the time of application.</li>
        <li>AI-generated content may not reflect the most current market conditions, regulations, or economic data.</li>
        <li>Users <strong>MUST independently verify all data</strong>, analysis, and projections before making any financial or investment decisions.</li>
      </ul>

      <h2>4. Consult Licensed Professionals</h2>
      <p>
        NestCalc is a supplementary analysis tool designed to assist with preliminary investment
        evaluation. It is <strong>not a replacement for professional advice</strong>. Before making
        any real estate investment decision, you should:
      </p>
      <ul>
        <li><strong>Consult a licensed financial advisor</strong> to evaluate whether a particular investment is appropriate for your financial situation, risk tolerance, and goals.</li>
        <li><strong>Consult a licensed real estate professional</strong> (agent, broker, or appraiser) for accurate property valuations, comparable sales data, and local market conditions.</li>
        <li><strong>Consult a tax professional</strong> (CPA or enrolled agent) for guidance on tax implications of real estate transactions, including depreciation, 1031 exchanges, and capital gains.</li>
        <li><strong>Consult a licensed attorney</strong> for legal matters including contract review, entity structuring, landlord-tenant law, and regulatory compliance.</li>
      </ul>
      <p>
        The cost of professional advice is minimal compared to the financial risk of making an
        uninformed investment decision. Always seek qualified counsel.
      </p>

      <h2>5. Assumption of Risk</h2>
      <p>
        Real estate investment carries <strong>inherent and significant risks</strong>, including but
        not limited to: loss of principal, negative cash flow, property depreciation, market
        downturns, interest rate increases, tenant vacancy, unexpected maintenance costs, natural
        disasters, and changes in local, state, or federal regulations.
      </p>
      <p>By using the Service, you expressly acknowledge and agree that:</p>
      <ul>
        <li>All investment decisions you make are <strong>solely your responsibility</strong>. NestCalc provides tools — you make the decisions.</li>
        <li>NestCalc.ai, LLC, its owners, members, employees, contractors, and affiliates assume <strong>no liability whatsoever</strong> for any investment decisions you make or any financial outcomes — whether gains or losses — that result from your use of the Service.</li>
        <li>You agree to <strong>hold NestCalc.ai, LLC harmless</strong> from any and all claims, damages, losses, liabilities, costs, and expenses (including attorney's fees) arising from or related to your reliance on any output of the Service.</li>
      </ul>

      <h2>6. Data Accuracy</h2>
      <p>
        NestCalc makes reasonable efforts to provide accurate calculations and reliable data
        integrations. However:
      </p>
      <ul>
        <li><strong>No warranty is made</strong> — express or implied — regarding the accuracy, completeness, reliability, or timeliness of any output, calculation, projection, or data displayed by the Service.</li>
        <li>Software bugs, API outages, data feed interruptions, third-party service failures, and caching delays may affect the accuracy of results at any time.</li>
        <li>Mortgage rates, economic indicators, and market data are sourced from third-party APIs and may be delayed, cached (up to 6 hours), or temporarily unavailable.</li>
        <li>Users should <strong>cross-reference all outputs</strong> with independent, authoritative sources before making any decisions.</li>
      </ul>
      <p>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER
        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2>7. Contact</h2>
      <p>If you have questions about this disclaimer, please contact us at privacy@nestcalc.ai.</p>
      <p><strong>Entity:</strong> NestCalc.ai, LLC — a Wyoming limited liability company</p>
      <p><strong>Effective Date:</strong> March 30, 2026</p>
    </>
  )
}
